- title: TogetherFlow
  subtitle: Human Motion in Immersive Rooms
  image: images/projects/togetherflow.png
  link: https://github.com/jerrymhuang/TogetherFlow
  description: >
    In a first-of-its-kind application, we use simulation-based inference for modeling
    human motion while experiencing shared virtual worlds, paving the way 
    for model-based research on human interaction with the built environment. 
  tags:
    - application